<a href="https://colab.research.google.com/github/Drich05/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [22]:
import numpy as np
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


Problem 2


In [21]:
import numpy as np 

#3x - y + z = 5
#9x - 3y +3z = 15
#-12x +4y -4z = -20 

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(a)
B = np.array([[5],[15],[-20]])
print(B)
x =  solve(A,B)
print(x)


[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


NameError: ignored

It cannot be solve because i think it is stopping due to the inverse of matrix if the inner dimensions of the matrices are equal the number of columns of the left matrix must match the number of rows in the right matrix.

Problem 3


In [ ]:
import numpy as np
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
w, v = np.linalg.eig(A)
print("Eigenvalues are \n ")
print(w.round())
print("Eigenvectors are \n ")
print(v.round())

Eigenvalues are 
 
[-1.  3.  2.]
Eigenvectors are 
 
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
