<a href="https://colab.research.google.com/github/Drich05/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMBER 1

NUMBER 2

NUMBER 3

NUMBER 4


NUMBER 5

NUMBER 6

In [8]:
import numpy as np

a = np.array([[5,4,1],[10,9,4 ],[10,13,15]])
inv_c= np.linalg.inv(c)
print(c)
print()
print(inv_c)

b = np.array([[3.4],[8.8],[19.2]])

x = np.dot(inv_c, b)
print()
print(x)

z = np.dot (c,x)
print()
print(z)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]

[[0.2]
 [0.4]
 [0.8]]

[[ 3.4]
 [ 8.8]
 [19.2]]
