<a href="https://colab.research.google.com/github/Drich05/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMBER 1

In [11]:
import numpy as np

#square matrix with same length and width 5x5
Squarematrix = np.array([[1,2,3,4,5],[2,4,6,8,10],[3,6,9,12,15],[4,8,12,16,20],[5,10,15,20,25]])
print("Squarematirix 5x5")
print(Squarematrix)

Squarematirix 5x5
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


NUMBER 2

In [12]:
import numpy as np

C = np.triu([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(C)

[[ 1  2  3  4  5]
 [ 0  7  8  9 10]
 [ 0  0 13 14 15]
 [ 0  0  0 19 20]
 [ 0  0  0  0 25]]


NUMBER 3

In [17]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

b = np.transpose(a)
print()
print(b)

c = np.matmul(a,b)
print()
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


NUMBER 4


In [13]:
import numpy as np 

C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C)
invC = np.linalg.inv(C)
print()
print("Inverse of Matrix C:")
print(invC)


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

Inverse of Matrix C:
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


NUMBER 5

In [16]:
import numpy as np
#Matrix 3x3
C = np.array([[1,2,3],
              [2,3,3],
              [3,4,-2]])
#to get the determinant of the matrix 
detC = np.linalg.det(C)

print("The determinant: \n")
print(int(detC))




The determinant: 

5


NUMBER 6

In [8]:
import numpy as np

a = np.array([[5,4,1],[10,9,4 ],[10,13,15]])
inv_c= np.linalg.inv(c)
print(c)
print()
print(inv_c)

b = np.array([[3.4],[8.8],[19.2]])

x = np.dot(inv_c, b)
print()
print(x)

z = np.dot (c,x)
print()
print(z)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]

[[0.2]
 [0.4]
 [0.8]]

[[ 3.4]
 [ 8.8]
 [19.2]]
