<a href="https://colab.research.google.com/github/Drich05/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,],[3,4,],[5,6,]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2,],[3,4,]])
print(A)
print()
print(B)
print()
print(C)
print()
print(D)
print()
dot = np.dot(A,B)
print(dot)
print()
print(D+D)
print()

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [3 4]]

[[22 28]
 [49 64]]

[[2 4]
 [6 8]]



In [4]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
S = 2*C
S

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
import numpy as np
O = np.array([5,3,-1])

print(O)
print()
print('Type:', type(O))
print('Shape:', O.shape)
print('Dimension:', O.ndim)

[ 5  3 -1]

Type: <class 'numpy.ndarray'>
Shape: (3,)
Dimension: 1
