<a href="https://colab.research.google.com/github/Drich05/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and Its Operations

In [1]:
import numpy as np
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a+b)


[[ 1 -3]
 [ 6  4]]


In [2]:
import numpy as np
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(b-a)

[[11 -3]
 [-2  2]]


In [3]:
import numpy as np
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]
